// M4-T1: bakes the Sentry DSN, release (commit) and environment into the
// bundle. Runs before `ng build` in CI/CD; a missing variable leaves tracking off.
import { writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';

const git = () => {
  try {
    return execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    return 'unknown';
  }
};
const env = {
  sentryDsn: process.env.SENTRY_DSN_WEB ?? '',
  release: process.env.SENTRY_RELEASE ?? git(),
  environment: process.env.SENTRY_ENVIRONMENT ?? process.env.APP_ENV ?? 'local',
};
writeFileSync(
  new URL('../src/env.generated.ts', import.meta.url),
  `// Generated by scripts/write-env.mjs — do not edit.\nexport const BUILD_ENV = ${JSON.stringify(env, null, 2)};\n`,
);
console.log(
  `env.generated.ts: release ${env.release}, environment ${env.environment}, sentry ${env.sentryDsn ? 'on' : 'off'}`,
);
