/**
 * PrimeNG Aura preset configured to the Hub brand without colliding with the
 * document-state palette (10-Screen-Specification §1, 03-Technical-Architecture §8.1).
 *
 * - Aura `primary` is NAVY, never gold. Aura paints primary on buttons, links,
 *   focus rings, active tabs and form accents, and gold #D9A441 sits in the same
 *   hue family as draft amber #B8730B. A gold primary would put gold beside a
 *   state pill on nearly every screen.
 * - Gold is a CSS variable (--brand-gold in styles.scss) used only for the logo,
 *   top-bar mark, sign-in and marketing. It has no PrimeNG token on purpose.
 * - Border radius is 4px on controls (documents themselves use 0 — see styles.scss).
 */
import { definePreset } from '@primeuix/themes';
import Aura from '@primeuix/themes/aura';

// Navy #1E2761 scale. 700 is the brand navy; lighter steps are for hover/focus
// surfaces, darker steps for pressed states. Generated by hand around the brand
// value so that 700 is exact.
const navy = {
  50: '#EEF0F7',
  100: '#D8DCEC',
  200: '#B3BAD9',
  300: '#8B96C3',
  400: '#65729F',
  500: '#3F4C87',
  600: '#2C3873',
  700: '#1E2761',
  800: '#171E4C',
  900: '#101537',
  950: '#0A0D22',
};

export const FlowZappPreset = definePreset(Aura, {
  primitive: {
    borderRadius: {
      none: '0',
      xs: '2px',
      sm: '4px',
      md: '4px',
      lg: '4px',
      xl: '4px',
    },
  },
  semantic: {
    primary: navy,
    focusRing: {
      width: '2px',
      style: 'solid',
      color: '{primary.700}',
      offset: '2px',
    },
    colorScheme: {
      light: {
        primary: {
          color: '{primary.700}',
          contrastColor: '#FFFFFF',
          hoverColor: '{primary.800}',
          activeColor: '{primary.900}',
        },
        highlight: {
          // ice #CADCFC: selection, focus halo, row hover — never large fills
          background: '#CADCFC',
          focusBackground: '#B3BAD9',
          color: '{primary.900}',
          focusColor: '{primary.900}',
        },
        surface: {
          0: '#FFFFFF', // --paper
          50: '#F2F4F6', // --rail
          100: '#E9ECEF',
          200: '#DDE2E7', // --line
          300: '#C8CFD6',
          400: '#9AA5B1',
          500: '#5B6B7C', // --ink-soft
          600: '#465565',
          700: '#33404E',
          800: '#242E3A',
          900: '#1E2761', // --ink
          950: '#101537',
        },
      },
    },
  },
});
